### ISSUE TITLE
Add b2sum/b3sum

### ISSUE THREAD

**Issue by gargullia** [GeopJr/Collision#102]
https://github.com/BLAKE3-team/BLAKE3

**Comment by GeopJr** [comment]
Thanks for raising this issue!

While BLAKE is awesome, I am not really interested in adding it at the moment.

Collision uses [Crystal's Digest functions (OpenSSL)](https://crystal-lang.org/api/1.5.0/Digest.html) (/ not `md5sum`, `sha1sum` etc) to calculate the hashes. Adding BLAKE would require a major rewrite + writing bindings for the C lib + linking against it.

I'll leave this issue open until I decide on how to approach more hash functions & I'll start a discussion for it.
