### ISSUE TITLE
Allow launching multiple instances

### ISSUE THREAD

**Issue by teackot** [GeopJr/Collision#104]
**Is your feature request related to a problem? Please describe.**
I find this app useful to check if two files are identical, right now I have to copy two hashes into a text editor and compare them there.

**Describe the solution you'd like**
Allow opening multiple windows of the app.

**Comment by GeopJr** [comment]
Thanks for raising this issue!

Allowing multiple instances does sound interesting and I'll definitely get on it, however your use case seems to be already covered:

1. Open the first file by clicking on the "Open File" button in the welcome view
![Screenshot of Collision's welcome view](https://user-images.githubusercontent.com/18014039/184704329-0ad37bf1-25eb-4fb5-9ada-491c0a8d6540.png)

2. Select the verify tab from the headbar:
![Screenshot of Collision's Hash view](https://user-images.githubusercontent.com/18014039/184704808-26c163f8-225e-4254-9e80-72424f0796e0.png)
![Screenshot of Collision's Verify view](https://user-images.githubusercontent.com/18014039/184704910-d7a72d06-38ee-439d-a29a-2df37c87cab4.png)

3. Click on the button under the title "File" and select the file you want to check against:
![Screenshot of Collision's Verify view, a file was selected under the file checking section that matches the main opened file](https://user-images.githubusercontent.com/18014039/184705046-d9d0d228-23c2-4ab3-a6c9-e11066552c7e.png)
![Screenshot of Collision's Verify view, a file was selected under the file checking section that doesn't match the main opened file](https://user-images.githubusercontent.com/18014039/184705089-c4b41906-bf82-4a0f-845d-1989939beb6f.png)


If that is not your use case, please explain it below!
If that was your use case, it appears that the current design of the Verify view is not clear enough...

(just to explain the usage of the verify tab: they are tools to check against the current open file

the text filed checks if the input matches any of the hashes of `foo.txt`
the file button checks if a hash of the selected file matches any of the hashes of `foo.txt`)

**Comment by teackot** [comment]
Oh! I guess I'm just blind and didn't check out the verify tab in a hurry, otherwise it's pretty obvious what this tab does. Anyway, I think multiple instances is still a good thing to have

**Comment by DodoLeDev** [comment]
With the ability to open files directly from the command line, you are _“theoretically”_ able to open multiple files with Collision.
But for now, the program just doesn't handle it correctly!
It seems that launching a new instance of Collision......**merges the window content with the already-existing window!** xD

| First file | Second file | Sum of both |
| :---: | :---: | :---: |
| ![Capture d’écran du 2022-11-21 20-52-41](https://user-images.githubusercontent.com/59477313/203147538-8aa17458-94eb-4fd2-a73b-67d770012934.png) | ![Capture d’écran du 2022-11-21 20-52-53](https://user-images.githubusercontent.com/59477313/203147551-ac78f6c9-0e76-4806-ab29-1e65ca9809f2.png) | ![Capture d’écran du 2022-11-21 20-53-40](https://user-images.githubusercontent.com/59477313/203147570-7c43665b-e46f-432a-8142-937bf8fb3b36.png) |

**Comment by GeopJr** [comment]
Nice catch! Thanks for the report!

It should be fixed as of #124
