### ISSUE TITLE
Misalignment of texts in the check tab

### ISSUE THREAD

**Issue by DodoLeDev** [GeopJr/Collision#139]
**Describe the bug**
In the “Check” tab, if you narrow the window, in such a way the “checksum” or “file” string needs to use more lines than the other, the squares placed below them become misaligned!

**To Reproduce**
> **Note :** This bug only occurs if you have configured a language in Collision which translates the “checksum” or “file” string into multiple words (in French, for example, see attachment)
1. Open a file in Collision
2. Go to the “check” tab
3. Narrow the window, again and again, …
4. …until you see that squares becomes misaligned

**Expected behavior**
Both strings should be vertically aligned, and squares behind should stay aligned!

**Screenshots**
![image](https://user-images.githubusercontent.com/59477313/208271223-cf85e802-5496-4283-a0d6-653f24303c72.png)

**Environment (please complete the following information):**
 - OS: Arch Linux (btw)
 - Install method: AUR

**Comment by GeopJr** [comment]
Thanks for raising this issue! It should be fixed as of 6b5262505e160258652c2cd8c0d8fcbcb331d650
