### ISSUE TITLE
German Wikipedia article

### ISSUE THREAD

**Issue by gregorni** [GeopJr/Collision#146]
In the German translation of the app, the English Wikipedia article is used: https://github.com/GeopJr/Collision/blob/f4c4ab3583d7af85c6c0da0ee7c723e05004e090/po/de.po#L131

There is a similar comparison of Hash funcions in the German Wikipedia. However, it's not a page on it's own, but part of the page about cryptographic functions in general:

https://de.wikipedia.org/wiki/Kryptographische_Hashfunktion#%C3%9Cbersicht_von_Hashfunktionen

Should we use that instead of the English artcicle or not?

**Comment by GeopJr** [comment]
Sure!
