### ISSUE TITLE
Font size and colour options

### ISSUE THREAD

**Issue by HubKing** [GeopJr/Collision#154]
**Is your feature request related to a problem? Please describe.**
It is difficult to read in dark mode. The background is light grey and the text is also grey. 

**Describe the solution you'd like**
1. I wish I could set the font size.
2. I wish the contrast was higher (i.e., brighter text on darker background).

**Is it related to GNOME Human Interface Guidelines? Please add links.**

**Additional context**
![image](https://user-images.githubusercontent.com/10900489/227700899-147da947-ae7d-45fd-8d27-a7fc182ea381.png)

**Comment by GeopJr** [comment]
Thanks for raising this issue!

The colors and font size are part of the adwaita stylesheet and apps should probably avoid manually modifying them. Your concerns have already been raised upstream, you can keep track of it here: https://gitlab.gnome.org/GNOME/libadwaita/-/issues/593

You might find yourself in the same situation with other libadwaita apps as well and upstream might take some time to reach a decision so here's some solution you could try (but they might not be ideal):

- Use the high contrast theme - It should be under `Settings > Accessibility > Seeing` (or similar for non-GNOME DEs)
![image](https://user-images.githubusercontent.com/18014039/227714703-7895c715-0ecc-438a-96de-3d0b61612e41.png)
- Use the large text option - It should also be in the same category as the high contrast setting
![image](https://user-images.githubusercontent.com/18014039/227714759-5a82e17b-3e47-4fab-9828-c75266f996e4.png)
- (Advanced - might cause issues) Use [Gradience](https://flathub.org/apps/details/com.github.GradienceTeam.Gradience) and add the following under `Advanced > Custom CSS`:

```css
row label.subtitle {
 opacity: 1;
 font-size: medium;
}
```

**Comment by HubKing** [comment]
Thank you for the answer. To be honest, this app is not the only app which has this sort of problem, but most apps in dark theme in general. They use light gray text on grey background, which is especially look bad on my monitor which seems to have problems with gray colours. 

I know that Gnome has high-contrast accessibility, but the problem is that that feature is designed for people with visual impairment and renders unnecessary things ugly and (like everything is black and white and thick). Also with large font options, which make unwanted things too big, in my opinion.

I hope Adwaita or Gnome or whoever related would make dark mode more high-contrast by default, or create some sort of so-called AMOLED mode like on Android, since now that there are laptops with AMOLED screens, but I guess I would have to wait a very very long time until one of those come true.

**Comment by GeopJr** [comment]
I understand, sorry you have to deal with this. Your situation is quite specific and interferes with your daily usage of GNOME so I will suggest the following but keep in mind that you are pretty much on your own, it might cause unexpected issues with theming and I have personally never used it myself so I can't provide further support:

With Gradience you can make an AMOLED-like theme, in fact there are two curated themes that might be that already (though, there are no screenshots) 
![image](https://user-images.githubusercontent.com/18014039/227715806-61330e7b-b057-4f1f-83f3-363e88047a3c.png)
