### ISSUE TITLE
[Request]: Validate appdata

### ISSUE THREAD

**Issue by sabriunal** [GeopJr/Collision#180]
### Describe the request

Many GNOME apps and related applications validate their metadata and desktop files using appstreamcli or related tools. 

The Collision app does not appear to be integrated with these validation tools. Utilizing these tools could help identify errors before the new release is pushed to repositories.

### Implementation Details

- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment]
Meson doesn't have Crystal support yet so it can't be as integrated as other projects but would adding it to the CI and the makefile be good enough?

**Comment by sabriunal** [comment]
I see some apps have been broken on GNOME Software due to some appdata mistakes. Any kind of validation would be useful.
