### ISSUE TITLE
Translatable developer and application names

### ISSUE THREAD

**Issue by yakushabb** [GeopJr/Collision#193]
### Describe the bug

It seems I was wrong about untranslatable developer and application names.

If you think these areas should be translatable you can remove translatable=no tags.

Sorry for my mistake.

https://github.com/GeopJr/Collision/blob/main/data/dev.geopjr.Collision.metainfo.xml.in#L7-L10

### Steps To Reproduce

-

### Logs and/or Screenshots

-

### Operating System

-

### Package

Flatpak

**Comment by GeopJr** [comment]
I want to keep it untranslatable, thanks for bringing it up!
