### ISSUE TITLE
Drag N Drop

### ISSUE THREAD

**Issue by Doomsdayrs** [GeopJr/Collision#53]
**Is your feature request related to a problem? Please describe.**
I opened this application to quickly do a hash gen.
I took the file, and did a DnD from the File Manager. 
I noticed, it did not load :cry: 

**Describe the solution you'd like**
Support DnD to hash a file

**Comment by GeopJr** [comment]
Thanks for raising this issue!

Currently there's a blocking issue, as far as I'm aware, that prevents me from adding DnD again. While there's a portal for it, it [hasn't been backported to GTK3 yet](https://gitlab.gnome.org/GNOME/gtk/-/issues/3094) and since Nautilus(/ GNOME Files) is still GTK3 (on the majority of distros at least), DnD will not work.

I'll give it another try when I get the time to, but for now I'll mark it as stalled.

**Comment by oscfdezdz** [comment]
DnD is already fixed in [GTK 4.8.1](https://gitlab.gnome.org/GNOME/gtk/-/commit/3a941eff4aa0ad66e0aa34e6528bc4d78c5e5d5e) and since Nautilus 43 will also be in GTK4, there should be no blockers left.

**Comment by GeopJr** [comment]
Thanks for letting me know! I'll get on this as soon as possible!

**Comment by DodoLeDev** [comment]
Nautilus v43.0 and still no Drag'n'drop! :cry:
![image](https://user-images.githubusercontent.com/59477313/199284976-21491cda-08fd-45d6-aeee-1250b4b593f3.png)

Also, could it be possible to add an option directly in the nautilus right-click menu?

**Comment by GeopJr** [comment]
Sorry about the wait, there's currently an issue with drag-n-drop and the portal so it has to stay as a draft until it gets fixed.

> Also, could it be possible to add an option directly in the nautilus right-click menu?

No, I don't think that's possible to do without an extension.

What I can do however is upstream some of the changes in the drag-n-drop PR and add Collision in the "Open With..." context entry:

[Recording of a GNOME desktop with the Files app open. There's a file named test.txt. User right clicks it and selects the open with context entry. Afterwards, a popup to select the app to open it with shows up. User selects Collision. Then the Collision up shows up with that file's hashes.](https://user-images.githubusercontent.com/18014039/199318847-7abcab58-d9be-4735-bf2c-8bb50cec8d5d.webm)
