### ISSUE TITLE
Flathub protal directory

### ISSUE THREAD

**Issue by Eonfge** [GeopJr/Collision#57]
**Describe the bug**
When you open an app with the Flatpak version of the App, you see the portal-location of the file and not the actual file location.

![Screenshot from 2022-03-15 10-29-30](https://user-images.githubusercontent.com/33983090/158348258-2d59146c-556c-4c3e-bfe2-0eb6e3eb070c.png)

**Expected behavior**

To fix this, you should take a closer look at the NativeFileChooserApi spec. There is a specific method to get the actual location and not the security-portal symlink.

https://docs.gtk.org/gtk4/class.FileChooserNative.html

**Environment (please complete the following information):**
 - OS: Fedora Linux 35
 - Install method: Flathub

**Comment by GeopJr** [comment]
Thanks for raising this issue!

Could you point me at that method? I can't seem to find it.
The closest I could find is [flatpak/xdg-desktop-portal#475](https://togithub.com/flatpak/xdg-desktop-portal/issues/475), which mentions adding host filesystem permission as a workaround. I'd like to avoid it unless there's no other solution.

**Comment by Eonfge** [comment]
> The closest I could find is [flatpak/xdg-desktop-portal#475](https://togithub.com/flatpak/xdg-desktop-portal/issues/475), which mentions adding host filesystem permission as a workaround. I'd like to avoid it unless there's no other solution.

That should not be necessary, and it's also undesirable: An application like yours that should help people secure their computer, should not rely on such a brute-force method.

By the sound of it, showing the full path seems to be impossible right now. I didn't know that, so perhaps it's best to put it on the to-do list. For now, as a 'triage' you can just not display the file-path inside a flatpak. Bit blunt, but it solves the confusion it otherwise creates.

**Comment by GeopJr** [comment]
That sounds like the best solution at the moment. I'll add a runtime check just in case someone gives it host filesystem permission manually. Thanks!
