### ISSUE TITLE
Chinese translation not work

### ISSUE THREAD

**Issue by lumingzh** [GeopJr/Collision#58]
**Describe the bug**
The simplified Chinese translation not work for Collision.

**To Reproduce**
1. install from flathub
2. start collision
3. the app UI displayed in English

**Expected behavior**
Displayed in Chinese.

**Environment (please complete the following information):**
 - OS: Fedora Silverblue 35
 - Install method: flathub

**Additional context**
You can see the terminal messages of app running in four different environments bellow:
![2022-03-15 18-32-23 的屏幕截图](https://user-images.githubusercontent.com/89230850/158359233-511f4d34-697c-4bc1-ae67-fd9c720c2490.png)
 
I don't know if it relates to the same bug of [Bottles](https://github.com/bottlesdevs/Bottles/issues/574) and [Junction](https://github.com/sonnyp/Junction/issues/61).

**Comment by lumingzh** [comment]
@GeopJr Yes, my system language always simplified Chinese. But I think the language code should be zh_CN not zh_Hans, I'm not sure if GNOME can recognize zh_Hans. This issue may be relate to [this setting of weblate](https://github.com/WeblateOrg/weblate/discussions/5666), not sure.

**Comment by GeopJr** [comment]
So, I added `zh_CN` as an alias to `zh_Hans` on Weblate (https://hosted.weblate.org/projects/collision/collision/zh_CN should redirect to `zh_Hans`) and copied the `zh_Hans.po` to  `zh_CN.po`. Hopefully next time Weblate makes a PR it will update both, if it doesn't I'll update it manually or make a github action. Thanks!

**Comment by lumingzh** [comment]
@GeopJr I will test it after you published new version on flathub. About the duplicate translations, I think you can view [Celluloid](https://github.com/celluloid-player/celluloid/tree/master/po)(gnome-mpv) for reference, Celluloid from flathub works perfectly on fedora silverblue. Celluloid doesn't use zh_Hans po file, but I'm still not sure if it's weblate's problem or not before I test it.

**Comment by GeopJr** [comment]
Thanks for the info! Following Celluloid, I removed zh_Hans in favor of zh_CN. It will be in the next release!

**Comment by GeopJr** [comment]
3.0.1 seems to have fixed it! (It should be available in the repo in some hours)

![Collision main view in zh_CN](https://user-images.githubusercontent.com/18014039/160307114-0f7eacd6-67fe-4907-bacc-7a3a7375bf77.png)

**Comment by lumingzh** [comment]
@GeopJr Great! I test it after updated and works normal, thank you.
