### ISSUE TITLE
Misaligned checksum and file cards with translated strings

### ISSUE THREAD

**Issue by oscfdezdz** [GeopJr/Collision#64]
**Describe the bug**
Misaligned checksum and file cards when translated strings are more than one line long at the default window size.

**To Reproduce**
- Test Collision with translations where "Checksum" or "FIle" are two lines long.

**Expected behavior**
That the two cards were aligned.

**Screenshots**
![image](https://user-images.githubusercontent.com/42654671/159099287-c58e50d2-e2bc-4872-92b8-b03c5b93ea1e.png)

**Environment (please complete the following information):**
 - OS: Fedora Silverblue 36
 - Install method: GNOME Builder

**Additional context**
It is solved when the window size is increased to a size large enough for the string to fit on one line.

**Comment by GeopJr** [comment]
Thanks for raising this issue!

This is caused from the use of StatusPage for each tool.

Quick brainstorming: replace them with a grid with the top row being labels (title class) and bottom row the tools. This will also solve #62
