### ISSUE TITLE
Case sensitive

### ISSUE THREAD

**Issue by youssef20031** [GeopJr/Collision#86]
**Describe the bug**
When comparing a file to a correct hash and it is written in full capital letters it gives that the hash is false despite it being true

**To Reproduce**
1. Open file
2. Put a full capital hash

**Expected behavior**
To verify as correct

**Environment (please complete the following information):**
 - OS: Fedora 36
 - Install method: Flathub

**Comment by GeopJr** [comment]
Thanks for raising this issue!

It has been fixed in #84 and will be available with the next release!
